### ISSUE TITLE
You should continue with development

### ISSUE THREAD

**Issue by BenHayat** [TanvirArjel/EFCore.GenericRepository#1]
Firstly, thank you on working on such needed library. Regardless of how many stars (*) you get, you continue working on the and make it better. As times goes people will see value.

..Ben

**Comment by TanvirArjel** [comment]
@BenHayat Thank you so much for your inspiring words. Surely I shall continue to develop this library. Please submit issues if you find or feature request if needed. I shall fix or add these as soon as possible.

**Comment by BenHayat** [comment]
> 
> 
> @BenHayat Thank you so much for your inspiring words. Surely I shall continue to develop this library. Please submit issues if you find or feature request if needed. I shall fix or add these as soon as possible.

What I wrote to you, is something I say to myself everyday for my app. "Build it first, then people will come". If you build something that people need (and a solid repository is one), then it will expand. Just do it to fulfill your desire.

I'll be looking into docs now and give it some serious look & test and keep you posted.
Thanks for creating it.

**Comment by BenHayat** [comment]
I also suggest to offer a sample app that can guide people on setting up Entities and related files and folders.
This way,it helps where everyone uses a prescribed pattern.
