### ISSUE TITLE
Proper use of your library by multiple projects?

### ISSUE THREAD

**Issue by BenHayat** [TanvirArjel/EFCore.GenericRepository#2]
Hi Tanvir;

I'd like to ask your opinion for the proper way to use your library by multiple projects, and yet, have a central location to maintain migrations process.

Suppose I have a Blazor server side (which is pretty much like an ASP.Net Core Razor pages, and I have another project which is Web API. And I want to use your library among these two or more project.
Here is my approach and you tell me if it is correct or if there is a better way.

a) I would create a new Class Library based on .Netcore 3.1 (Data Access Layer) which will reference EntityFrameworkCore library.

b) This library will also reference another shared project that holds all the entities (for API, Blazor server & Blazor client)

c) I then bring in your library into this Data Access Layer, **and create my "ApplicationDbContext" class in this module.**

**d) Then in each Project (API, Blazor Server and Blazor), I will register the "ApplicationDBContext" with DI and provide the Connection string in each project's App settings. 
This way, when each project is running, they inject an instance of ApplicationDBContext to DataAccessLayer and then pass it to your library in DAL**.

DAL will have the folder for all migrations.

Is this a proper setup to ensure each calling project, instantiate an instance of ApplicationDBContext, sends it to DAL and also DAL maintains a central location for migrations?
If there is a better way, please let me know.

Perhaps you can create a simple solution with and ASP Core, WebAPI and DataAccessLibrary to show the proper placements of all the parts.

Thanks!
..Ben

**Comment by TanvirArjel** [comment]
@BenHayat Thank you so much for your comment and for asking suggestions. Please send me a private email to my profile displayed email so that I can help you in this regard.
