### ISSUE TITLE
Can you do the automapper.odata support or is it redundant?

### ISSUE THREAD

**Issue by mansurdegirmenci** [TanvirArjel/EFCore.GenericRepository#21]
I am using "odata" in my web api project. and "automapper" has that data support.
https://github.com/AutoMapper/AutoMapper.Extensions.OData

my method:
```
[HttpGet]
[EnableQuery]
public IActionResult Get(ODataQueryOptions<MyInternetHatlariDto> options)
{
//I don't want to use "context" how can I use your library here.
return Ok(_context.MyInternetHatlaris.Get(_mapper, options));
}
```

I also use your library. but since this is not supported, I have to use the database object directly. Do you think support should come or is it unnecessary?

**Comment by TanvirArjel** [comment]
@mansurdegirmenci Thank you so much for your issue. Currently, we don't have any plans.
