### ISSUE TITLE
Documentation unitofwork

### ISSUE THREAD

**Issue by ChristPetitjean** [TanvirArjel/EFCore.GenericRepository#3]
Hello,
You're project seem promising!
Could you add documentation over unitofwork?
Ex: modifying many entities from différents repo and commit or rollback every one's at once 😁

**Comment by TanvirArjel** [comment]
@ChristPetitjean Thank you so much for your feedback. Actually, UnitOfWork based generic repository is going to be removed from version 6.0.0 and it has been already been marked as obsolete in version 5.0.0. The same functionality is being offered with the `IRepository` interface.
