### ISSUE TITLE
Client side evaluation

### ISSUE THREAD

**Issue by joshua1** [TanvirArjel/EFCore.GenericRepository#4]
Hi @TanvirArjel Nice library here. I wanted to ask if you considered the drop in support of client side evaluation in query conditions, and how that is handled here . especially in specification where you use extension methods like Contains, Any etc)

**Comment by TanvirArjel** [comment]
@joshua1  Thank you for your comment. Client-side evaluation is already disabled. 

>  especially in the specification where you use extension methods like Contains, Any etc)

Could you please give an example of what you are actually wanting?
