### ISSUE TITLE
Why should we use this library?

### ISSUE THREAD

**Issue by mogaozq** [TanvirArjel/EFCore.GenericRepository#5]
I have came across a question engaging my mind. 
We Implement Repository pattern to decouple our logic from data-layer.
By using your generic repository we are coupling logic layer with this library.

**Comment by TanvirArjel** [comment]
> We Implement a Repository pattern to decouple our logic from the data-layer.

No! Repository itself a data access layer. We write a repository to separate data access code from our application logic.
