### ISSUE TITLE
Q: How to use transctions

### ISSUE THREAD

**Issue by ChristPetitjean** [TanvirArjel/EFCore.GenericRepository#6]
I am trying your repository.

I am in a situation where i should delete a data, insert another one and if insert is ok, get the id of inserted to put it in  an history table (no foreign key here).

To do this, I need to open a transction manually, put several `SaveChanges` and if everything is ok commit the transaction (obviously, if something went wrong, rollback the transaction ~_~)

Is it possible with this repository ?

**Comment by TanvirArjel** [comment]
@ChristPetitjean Thank you so much for contacting us. Currently, you must have a relationship between your main table and the history table then you can do all the things you mentioned with a single SaveChanges.

**Comment by ChristPetitjean** [comment]
Added pull request as an example #7

**Comment by TanvirArjel** [comment]
@ChristPetitjean Thank you so much for your pull request. I shall go through your code and take a decision.

**Comment by TanvirArjel** [comment]
@ChristPetitjean Transaction support has been added. So you can do as follows:

    public async Task<int>> CreateAsync(Employee employee)
    {
            IDbContextTransaction transaction = await _repository.BeginTransactionAsync(IsolationLevel.ReadCommitted);
            try
            {
                object[] primaryKeys = await _repository.InsertAsync(employee);
                
                long employeeId = (long)primaryKeys[0];
                EmployeeHistory employeeHistory = new EmployeeHistory()
                {
                    EmployeeId = employeeId,
                    DepartmentId = employee.DepartmentId,
                    EmployeeName = employee.EmployeeName
                };

                await _repository.InsertAsync(employeeHistory);

                await transaction.CommitAsync();
                
                return employeeId;
            }
            catch (Exception)
            {
                await transaction.RollbackAsync();
                throw;
            }
    }
