### ISSUE TITLE
how to use multiple dbcontext?

### ISSUE THREAD

**Issue by byung-hyun-nah** [TanvirArjel/EFCore.GenericRepository#8]
i want used multiple dbcontext

because my database is multiple

but exemple is only once used dbcontext

waiting for your answer

**Comment by TanvirArjel** [comment]
@byung-hyun-nah You have to use the factory pattern after registering all the `DbContext`s and multiple instances of  `services.AddGenericRepository<DemoDbContext>();`.

**Comment by dresswithpockets** [comment]
Care to share an example of how you would do this with your current pattern? When you say factory, I'm assuming you mean something like:

```cs
interface IRepositoryFactory<T> where T : DbContext {
    IRepository GetRepository();
}

class RepositoryFactory<T> : IRepositoryFactory<T> where T : DbContext {

    private readonly T _context;
    private IRepository? _repository;

    public RepositoryFactory(T context) => _context = context; 

    public IRepository GetRepository() => _repository ??= new Repository(_context);
}
```

only issue is `Repository` is internal so this wouldn't work. Theres no reasonable way to get an `IRepository` with a dbcontext of type `T` without reflection. Am i missing something here?
